language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install 'requests<2.11.0'; fi
  - pip install -r requirements.txt
  - pip install responses
script: python -m unittest test.client
